### ISSUE TITLE
--target option

### ISSUE THREAD

**Issue by DylanPiercey** [antonmedv/jsize#10]
I've been noticing that some people are also starting to care more about server side dependency bulk and was thinking it might be a good idea to start supporting something like `--target=node`.

In the same vein I was thinking it would also be cool to display the actual tarbal size.

@antonmedv what are your thoughts on these features?

**Comment by antonmedv** [comment]
How people will discover this functionality? Maybe it's better to show this in verbose mode?

**Comment by DylanPiercey** [comment]
Are you referring to the target option or tarbal sizes? Using verbose mode for tarbal sizes was my initial thinking. As far as the target option goes, a help menu for this module could be beneficial.

Previously been trying to conceive of a way to make it so that users can supply their own webpack loaders, like: `jsize --loaders=marko:marko-loader marko/components` but it opens a whole can of worms. Curious what your thoughts on that are as well though.

---

Edit: Just remembered that we are already using commander for help menus https://github.com/antonmedv/jsize/blob/master/bin/jsize#L19 so we can just add it to the docs there.

**Comment by antonmedv** [comment]
Does bundle size differs when targeting node?

**Comment by antonmedv** [comment]
I think `--target` can be okay as well.

**Comment by DylanPiercey** [comment]
Many packages will have different sizes because of the 'browser' field in the package json. This is for any isomorphic package or framework.

**Comment by antonmedv** [comment]
So there are only two targets? browser and node? Maybe add `-n, --node` options instead?

**Comment by DylanPiercey** [comment]
Also the browser target adds shims for all of the node stdlib, which adds some bulk that is not needed for node.

I'm not against a node option, although webpack has many targets so it may be good to support them all with `--target <target>`.

**Comment by antonmedv** [comment]
So what you think is better `--target node` or `--node`? `-t node` or `-n`?

**Comment by DylanPiercey** [comment]
IMO `--target node` is best. Because we can also support `--target electron-renderer` and `--target node-webkit` which are different still (they use the 'browser' field but not shims for the stdlib).

**Comment by antonmedv** [comment]
Okay 👍

**Comment by DylanPiercey** [comment]
I started digging into this to implement it, however I realized it's a bit trickier than I initially thought because of resolving the input file also depends on the target.

I'll probably get around to it in a few days.
