### ISSUE TITLE
Add + plus operator

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#17]
For calc sums
```
jsize react + react-dom + redux
```

**Comment by DylanPiercey** [comment]
This is a great idea.

**Comment by DylanPiercey** [comment]
@antonmedv do you think `react+react-dom` (no spaces) is acceptable? This way it is easier to parse with commander and we can more easily do stuff like `react+react-dom jquery`.

Also as far as output goes I'm thinking this:

```console
$ jsize react+react-dom jquery
✔ react + react-dom        51.12 kB (gzip)
✔ jquery                    30.6 kB (gzip)
```

**Comment by antonmedv** [comment]
Will be cool to support `jsize react + react-dom` with spaces. Users can do strange stuff.
