### ISSUE TITLE
Use text-table in verbose mode

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#18]
What about using https://www.npmjs.com/package/text-table in -v?

**Comment by DylanPiercey** [comment]
I'm all for using a better table format, however I'm not sure how to do it given that the package sizes load async one after the other. Looks like this lib requires all in one go.

**Comment by antonmedv** [comment]
We can create something similar.

**Comment by DylanPiercey** [comment]
I actually figured out how to do this. Going to sleep in a sec but I'll push some stuff tomorrow.
