### ISSUE TITLE
Support relative files.

### ISSUE THREAD

**Issue by DylanPiercey** [antonmedv/jsize#21]
Was just thinking it'd be kinda cool to support stuff like `jsize ./my-local-file.js`.
Curious on your thoughts @antonmedv.

**Comment by antonmedv** [comment]
That's be cool. But how to deal with imports?

**Comment by DylanPiercey** [comment]
Would be resolved with webpack so we wouldn't have to worry. Basically we would just skip the install step for relative files.

**Comment by antonmedv** [comment]
Yes, but that's can be tricky as user's webpack config can contain resolve and other stuff.
```
import something from 'app/root/path/something'
```

```
import 'style.css'
```

**Comment by DylanPiercey** [comment]
Yeah your right, it'd probably be more confusing to users than it's worth.
