### ISSUE TITLE
Error with monkberry

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#24]
Can't get monkberry size:
```
$ jsize monkberry
✖ Refusing to delete /var/folders/jz/2vkj2mlx1kl_mkbp2y41sxcr0000gn/T/node_modules/.bin/monkberry: 
containing path /var/folders/jz/2vkj2mlx1kl_mkbp2y41sxcr0000gn/T/node_modules/monkberry isn't under npm's control
```

**Comment by DylanPiercey** [comment]
I think I have seen this one but haven't been able to replicate it. I think when I encountered it I `rm -rf`'d the node_modules folder. We should try to find out why this happens though, probably something related to the temp folder.
