### ISSUE TITLE
Lag with stderr

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#33]
Try `jsize preact` and you will see a lag which leads to output like this:
```

   preact  =  ⠏

   preact  =  3.73 kB (gzipped)
```
I think it's because of some stderr of npm install. 

Maybe it's better to fork process while installing to get full control of stdout and stderr and do not monkey patch console.log.

**Comment by DylanPiercey** [comment]
@antonmedv what do you think the best way to approach this is?

**Comment by antonmedv** [comment]
Isolate npm install to separate process.

**Comment by DylanPiercey** [comment]
I don't think the issue is actually with npm install, but with webpack/minify/gzip. Even if you skip npm you still have the lag because one of these tasks (maybe even all) are blocking and slow.

**Comment by DylanPiercey** [comment]
After digging into it, it appears that uglify is the main culprit.

---

Also why are we minifying in two places ? https://github.com/antonmedv/jsize/blob/master/index.js#L110 and https://github.com/antonmedv/jsize/blob/master/index.js#L58

We should probably remove https://github.com/antonmedv/jsize/blob/master/index.js#L110

**Comment by antonmedv** [comment]
Agree

**Comment by DylanPiercey** [comment]
@antonmedv I've got a solution for this. After the https://github.com/antonmedv/jsize/pull/43 and https://github.com/antonmedv/jsize/pull/40 land then I will create a new PR. After that we can work on https://github.com/antonmedv/jsize/issues/15 and finally do a new release and be done for a while 😜.
