### ISSUE TITLE
Auto-switch targets

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#37]
When we get error like this:
```
Error: Can't resolve 'module'
```
Automatically calculate again with `-t node`.

This will help a lot of users.

**Comment by DylanPiercey** [comment]
What is an example package that has this error? I haven't seen this happen before.

**Comment by antonmedv** [comment]
Try this – `jsize r2`

**Comment by DylanPiercey** [comment]
[r2](https://www.npmjs.com/package/r2) includes gulp which is a bit complicated. In fact it doesn't compile properly regardless of target, not 100% sure why yet.

Also IMO it should not auto switch targets as this is confusing for the user and there is no possible way to know for sure the intended target, I'd say more helpful error messages are best.
