### ISSUE TITLE
Error on Windows machine

### ISSUE THREAD

**Issue by kfalkiewicz** [antonmedv/jsize#45]
Hi
When Want to use jsize i get this error every time. (Windows 7, system terminal)
![image](https://user-images.githubusercontent.com/1431712/30268929-9292433a-96e7-11e7-8681-1bf1c6351256.png)

**Comment by antonmedv** [comment]
Try bash for windows.

**Comment by kfalkiewicz** [comment]
Hmm fine, but still this shouldn't be bash dependent.

**Comment by antonmedv** [comment]
Maybe npm dependent.

**Comment by kfalkiewicz** [comment]
Other tools installed using npm works fine, so this is not npm / windows issue for sure.

**Comment by DylanPiercey** [comment]
@antonmedv could be an execFile issue? Perhaps we could try using https://github.com/sindresorhus/execa ?

**Comment by antonmedv** [comment]
Yes, maybe execa will help.
