### ISSUE TITLE
Warn about node version

### ISSUE THREAD

**Issue by kevin940726** [antonmedv/jsize#8]
This package uses `padEnd` and it's only available (without flag) above node v8.0.0. Do you plan to support lower version of node? Or we can add a warning to `package.json` and README. Thx for your great work!

**Comment by DylanPiercey** [comment]
I'll try to dig into this today and setup CI for supporting older node versions. Thanks for bringing this up.

**Comment by DylanPiercey** [comment]
Should now support node >= 4 😀

**Comment by kevin940726** [comment]
Thx for your quick response! Awesome job 👍

**Comment by DylanPiercey** [comment]
Actually I got use to the automatic save feature in npm 5 and didn't update the package son accordingly. Just rolled out another release and all should be good now :).
