### ISSUE TITLE
Add nice logo to README.md

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#9]
What about creating a nice logo? 🍰

**Comment by DylanPiercey** [comment]
That'd be awesome, although I'm terrible at design.

**Comment by antonmedv** [comment]
What about this:
<img src="https://user-images.githubusercontent.com/141232/29957332-1d50d0be-8f17-11e7-91cc-2329a01d5b23.png" width="600">

**Comment by DylanPiercey** [comment]
Looks good to me, better than plain text for sure 😝.
